config/routes.rb
Rails.application.routes.draw do
  get 'bugs/add'
  get '/my-bugs' , to: 'bugs#index'
  get '/bugs/new' , to: 'bugs#goToProjectsIndex'
  get '/bugs/all-bugs' , to: 'bugs#goToProjectsIndex'
  get '/bugs/my-bugs' , to: 'bugs#goToProjectsIndex'
  get '/bugs/new-bugs' , to: 'bugs#goToProjectsIndex'
  resources :bugs
  get '/users/password/new', to: 'error#notDeveloped'
  get 'projects/index'
  devise_for :users
  root 'home#index'
  resources :projects
  get '/users/', to: 'users#index'
  get '/projects/:id/manage-members', to: 'projects#manage'
  post '/projects/:id/add-members', to: 'projects#addUserToProject'
  post '/projects/:id/remove-members', to: 'projects#removeUserFromProject'
  get '/search-users/:name', to: 'users#search'
  get '/error', to: 'error#notFound'
  get '/not-developed', to: 'error#notDeveloped'


  get '/projects/:id/report-bugs', to: 'bugs#new'
  post '/projects/:id/create-bug', to: 'bugs#create'
  get '/projects/:id/all-bugs', to: 'bugs#allBugs'
  get '/projects/:id/new-bugs', to: 'bugs#newBugs'
  get '/projects/:id/my-bugs', to: 'bugs#myBugs'

  post '/projects/:id/assign-bug', to: 'bugs#assignBug'
  post '/projects/:id/mark-bug', to: 'bugs#markBug'

  get '*all', to: 'error#notFound', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "*path", to: redirect('/error')
end

app/models/bug.rb
class Bug < ApplicationRecord
  include Filterable
  has_one_attached :bug_image

  belongs_to :project
  belongs_to :developer, :class_name => 'User', :foreign_key => 'developer_id', optional: true
  belongs_to :creator,  :class_name => 'User', :foreign_key => 'creator_id'

  validates :title, presence: true, length: { minimum: 5,  maximum: 255 }

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:create , :assignBug , :markBug]
  # GET /bugs
  # GET /bugs.json
  def index
    if current_user.user_type == 0
      goToProjectsIndex
    elsif current_user.user_type == 1
      @bugs = Bug.where( developer_id: current_user.id )
    elsif  current_user.user_type == 2
      @bugs = Bug.where( creator_id: current_user.id )
    end
  end

  def allBugs
    authorizeBug
    @bugs = Bug.where(project_id: @project_id)
  end

  def newBugs
    authorizeBug
    @bugs = Bug.where(project_id: @project_id , developer_id: nil)
  end

  def myBugs
    authorizeBug
    @bugs = Bug.where(project_id: @project_id , developer_id: current_user.id)
  end

  def show
    authorize @bug
  end

  def new
    @bug = Bug.new
    @bug.project_id = params[:id]
    authorize @bug
  end

  def edit
    authorize @bug
  end

  def create
    @bug = Bug.new(create_bug_params)

    #If a bug with same name exists in current project
    respond_to do |format|
      if Bug.where(project_id: params[:id] , title: @bug.title).exists?
        @bug.errors.add( :title , "must be unique throughout project")
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      elsif @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def goToProjectsIndex
    redirect_to projects_url
  end

  def update
    authorize @bug
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @bug
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #POST REQUESTS

  #This Function is called by POST request to assign bug to a member
  def assignBug
    projectId = params[:projectId]
    bugId = to_number( params[:bugId] )
    userId = current_user.id
    id = params[:id]
    if id != projectId
      render json: { code: false, reason: "Invalid request." }
    elsif bugId < 0
      render json: { code: false, reason: "Invalid request." }
    elsif ProjectUser.where(project_id: projectId, user_id: userId).exists?
      bug = Bug.find(bugId)
      if bug.project_id == to_number(projectId) && bug.developer_id.nil?
        bug.developer_id = current_user.id
        bug.save
        if bug.valid?
          render json: { code: true, reason: "Bug assigned successfully." }
        else
          render json: { code: false, reason: "Something went wrong. Please try again." }
        end
      else
        render json: { code: false, reason: "This bug is already assigned to a developer." }
      end
    else
      render json: { code: false, reason: "Invalid request." }
    end
  end


  #This Function is called by POST request to mark bug status
  def markBug
    projectId = params[:projectId]
    bugId = to_number( params[:bugId] )
    userId = current_user.id
    id = params[:id]
    if id != projectId
      render json: { code: false, reason: "Invalid request." }
    elsif bugId < 0
      render json: { code: false, reason: "Invalid request." }
    elsif ProjectUser.where(project_id: projectId, user_id: userId).exists?
      bug = Bug.find(bugId)
      if(bug.project_id == to_number(projectId) && bug.developer_id == current_user.id)
        if(bug.status == 0)
          bug.status = 1
        elsif bug.status == 1
          bug.status = 2
        end
        bug.save
        if bug.valid?
          render json: { code: true, reason: "Bug marked successfully." }
        else
          render json: { code: false, reason: "Something went wrong. Please try again." }
        end
      else
        render json: { code: false, reason: "Invalid request." }
      end
    else
      render json: { code: false, reason: "Invalid request." }
    end
  end

  private

    # This is the method that'll be called if Pundit un-authorizes the user
    def user_not_authorized
      redirect_to((request.referrer || root_path) ,notice: "Authorization error.")
    end

    #Converts a string to number appropriately
    def to_number(string)
      Integer(string || '')
      rescue ArgumentError
        0
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.where(id: params[:id])
      if @bug.exists?
        @bug = @bug.first
      else
        redirect_to "/my-bugs", notice: 'This bug does not exists.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :deadline, :issue_type, :status, :bug_image)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_bug_params
      params.require(:bug).permit(:title, :deadline, :issue_type, :status, :bug_image).merge(creator_id: current_user.id , status: 0 , project_id: params[:id])
    end

    def authorizeBug
      @project_id = to_number(params[:id])
      bug = Bug.new
      bug.project_id = @project_id
      authorize bug
    end

end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/add.html.erb
<h1>Bugs#add</h1>
<p>Find me in app/views/bugs/add.html.erb</p>

app/views/bugs/allBugs.html.erb
<p id="notice"><%= notice %></p>

<h1>Bugs</h1>

<% if @bugs.length > 0 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th>Type</th>
      <th>Status</th>
      <th>Deadline</th>
      <th>Creator</th>
      <th>Developer</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.title %></td>
        <td>
          <% if bug.issue_type == 0 %>
            Bug
          <% else %>
            Feature
          <% end%>
        </td>
        <td>
          <% if bug.status == 0 %>
            New
          <% elsif bug.status == 1 %>
            Started
          <% else %>
            <% if bug.issue_type == 0 %>
              Resolved
            <% else %>
              Completed
            <% end%>
          <% end%>
        </td>
        <td><%= bug.deadline.strftime("%d-%m-%Y %I:%M %p") %></td>
        <td><%= bug.creator.name %></td>
        <td>
          <% if bug.developer.nil? %>
              Not Assigned
          <% else%>
            <%= bug.developer.name %>
          <% end %>
        </td>
        <td><%= link_to 'View Bug', bug , {:class => "btn btn-info btn-xs"  }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br>
  <h4>No bugs found.</h4>
<% end %>
<br>
<%= link_to 'Back', projects_url  , {:class => "btn btn-primary text-bold"  }%>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= form_with(model: @bug, local: true, multipart: true) do |form| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="field image-field">
    <%= form.label :bug_image %>
    <%= form.file_field :bug_image, accept: '.png, .gif' %>
  </div>

  <!--<div class="field long-select">
    <%= #form.label :status %>
    <%= #form.select :status , options_for_select([["New", 0], ["Started", 1], ["Resolved", 2]])  %>
  </div>
-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Bugs</h1>

<% if @bugs.length > 0 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th>Type</th>
      <th>Status</th>
      <th>Deadline</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.title %></td>
        <td>
          <% if bug.issue_type == 0 %>
            Bug
          <% else %>
            Feature
          <% end%>
        </td>
        <td>
          <% if bug.status == 0 %>
            New
          <% elsif bug.status == 1 %>
            Started
          <% else %>
            <% if bug.issue_type == 0 %>
              Resolved
            <% else %>
              Completed
            <% end%>
          <% end%>
        </td>
        <td><%= bug.deadline.strftime("%d-%m-%Y %I:%M %p") %></td>
        <td><%= link_to 'View Bug', bug , {:class => "btn btn-info btn-xs"  }%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <br>
  <h4>No bugs found.</h4>
<% end %>
<br>
<%= link_to 'Back', projects_url  , {:class => "btn btn-primary text-bold"  }%>

app/views/bugs/myBugs.html.erb
<p id="notice"><%= notice %></p>

<h1>My Bugs</h1>

<% if @bugs.length > 0 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th>Type</th>
      <th>Status</th>
      <th>Deadline</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.title %></td>
        <td>
          <% if bug.issue_type == 0 %>
            Bug
          <% else %>
            Feature
          <% end%>
        </td>
        <td>

          <% @typeStatusName = "Resolved" %>
          <% if bug.issue_type == 1 %>
            <%  @typeStatusName = "Completed" %>
          <% end%>

          <% if bug.status == 0 %>
            <% @typeStatusName = "Started" %>
            New
          <% elsif bug.status == 1 %>
            Started
          <% else %>
            <%= @typeStatusName%>
          <% end%>
        </td>
        <td><%= bug.deadline.strftime("%d-%m-%Y %I:%M %p") %></td>
        <td>
          <% if bug.status != 2 %>
            <input type="button" class="btn btn-xs btn-info" value="Mark <%= @typeStatusName%>" onclick="markBug(<%= bug.id %>)">
          <% end %>
        </td>
        <td><%= link_to 'View Bug', bug , {:class => "btn btn-info btn-xs"  }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br>
  <h4>No bugs found.</h4>
<% end %>
<br>
<%= link_to 'Back', projects_url  , {:class => "btn btn-primary text-bold"  }%>

app/views/bugs/new.html.erb
<div class="site-content">
<h3>Report New Bug/Feature</h3>

<%= form_with(model: @bug, local: true, multipart: true , :url => "create-bug") do |form| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="field image-field">
    <%= form.label :bug_image %>
    <%= form.file_field :bug_image, accept: '.png, .gif' %>
  </div>

  <div class="field long-select">
    <%= form.label :issue_type %>
    <%= form.select :issue_type , options_for_select([["Bug", 0], ["Feature", 1]])  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', "/" %>
</div>

app/views/bugs/newBugs.html.erb
<p id="notice"><%= notice %></p>

<h1>Bugs</h1>

<% if @bugs.length > 0 %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Project</th>
      <th>Type</th>
      <th>Status</th>
      <th>Deadline</th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.title %></td>
        <td><%= bug.project.title %></td>
        <td>
          <% if bug.issue_type == 0 %>
            Bug
          <% else %>
            Feature
          <% end%>
        </td>
        <td>
          <% if bug.status == 0 %>
            New
          <% elsif bug.status == 1 %>
            Started
          <% else %>
            <% if bug.issue_type == 0 %>
              Resolved
            <% else %>
              Completed
            <% end%>
          <% end%>
        </td>
        <td><%= bug.deadline.strftime("%d-%m-%Y %I:%M %p") %></td>
        <td>
          <input type="button" class="btn btn-xs btn-success" value="Assign Bug" onclick="assignBug(<%= bug.id %>)">
        </td>
        <td><%= link_to 'View Bug', bug , {:class => "btn btn-info btn-xs"  }%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <br>
  <h4>No bugs found.</h4>
<% end %>
<br>
<%= link_to 'Back', projects_url  , {:class => "btn btn-primary text-bold"  }%>

app/views/bugs/show.html.erb
<style type="text/css"> p {font-size: 16px; }</style>
<p id="notice"><%= notice %></p>

<h3>
  <strong>Title:</strong>
  <strong><%= @bug.title %></strong>
</h3>
<br><br>

<p>
  <strong>Deadline:</strong>
  <strong><%= @bug.deadline.strftime("%d-%m-%Y %I:%M %p") %></strong>
</p>

<p>
  <strong>Type:</strong>
  <% if @bug.issue_type == 0 %>
    Bug
  <% else %>
    Feature
  <% end%>
</p>

<p>
  <strong>Status:</strong>
  <% if @bug.status == 0 %>
    New
  <% elsif @bug.status == 1 %>
    Started
  <% else %>
    <% if @bug.issue_type == 0 %>
      Resolved
    <% else %>
      Completed
    <% end%>
  <% end%>
</p>

<p>
  <strong>Project:</strong>
  <%= @bug.project.title %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @bug.creator.name %>
</p>

<p>
  <strong>Developer:</strong>
  <% if @bug.developer.nil? %>
      Not Assigned
  <% else%>
    <%= @bug.developer.name %>
  <% end %>
</p>
<p>
  <% if @bug.bug_image.attached? %>
  <!-- @bug.bug_image.present? will always return true, use attached? to check presence -->
    <button class="btn btn-primary btn-xs" onclick="$('#imageWrap').toggle('slow')">Show Image</button>
    <p id="imageWrap" style="display: none;">
      <%= image_tag @bug.bug_image %>
    </p>
  <% end %>
</p>
<br><br>
<%= link_to 'Back', (request.referrer || root_path) , {:class => "btn btn-info btn-xs"  }%></td>