config/routes.rb
Rails.application.routes.draw do
  get 'bugs/add'
  get '/my-bugs' , to: 'bugs#index'
  get '/bugs/new' , to: 'bugs#goToProjectsIndex'
  get '/bugs/all-bugs' , to: 'bugs#goToProjectsIndex'
  get '/bugs/my-bugs' , to: 'bugs#goToProjectsIndex'
  get '/bugs/new-bugs' , to: 'bugs#goToProjectsIndex'
  resources :bugs
  get '/users/password/new', to: 'error#notDeveloped'
  get 'projects/index'
  devise_for :users
  root 'home#index'
  resources :projects
  get '/users/', to: 'users#index'
  get '/projects/:id/manage-members', to: 'projects#manage'
  post '/projects/:id/add-members', to: 'projects#addUserToProject'
  post '/projects/:id/remove-members', to: 'projects#removeUserFromProject'
  get '/search-users/:name', to: 'users#search'
  get '/error', to: 'error#notFound'
  get '/not-developed', to: 'error#notDeveloped'


  get '/projects/:id/report-bugs', to: 'bugs#new'
  post '/projects/:id/create-bug', to: 'bugs#create'
  get '/projects/:id/all-bugs', to: 'bugs#allBugs'
  get '/projects/:id/new-bugs', to: 'bugs#newBugs'
  get '/projects/:id/my-bugs', to: 'bugs#myBugs'

  post '/projects/:id/assign-bug', to: 'bugs#assignBug'
  post '/projects/:id/mark-bug', to: 'bugs#markBug'

  get '*all', to: 'error#notFound', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get "*path", to: redirect('/error')
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bug Zilla", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to('Welcome  '+ current_user.name, "#") %>
        </li>
        <li>
          <%= link_to "Home" , projects_url %></li>
        <li>
        <%= link_to('Edit Profile', edit_user_registration_path) %>
        </li>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
        <% else %>
          <li><%= link_to "Home" , "/" %></li>
          <li>
          <%= link_to('Login', new_user_session_path)  %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div id="notifier" class="notifier"></div>
    <%= yield %>
  </body>
</html>